// Emits dist/mono: a shebang wrapper that imports dist/mono.js under bun.
//
// Why a wrapper and not `bun --compile`? On recent macOS, the self-contained
// binary produced by `bun build --compile` fails Gatekeeper signature
// validation and gets killed with SIGKILL (exit 137) immediately at launch.
// Shipping a bundled JS file + a thin shebang wrapper avoids the issue
// entirely and keeps a single `dist/mono` entry point for the `bin` field
// and for bootstrap.sh to symlink.

import { writeFileSync, chmodSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const target = join(here, "..", "dist", "mono");

const content = `#!/usr/bin/env bun
// Auto-generated by scripts/emit-wrapper.ts — do not edit.
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
const here = dirname(fileURLToPath(import.meta.url));
await import(join(here, "mono.js"));
`;

writeFileSync(target, content, "utf8");
chmodSync(target, 0o755);
process.stdout.write(`wrote ${target}\n`);
